git:
  submodules: false
  depth: false

language: node_js

node_js:
  - "11"

addons:
  apt:
    packages:
      - build-essential
      - clang
      - libx11-dev
      - libxkbfile-dev
      - execstack
      - fakeroot
      - g++-4.8
      - git
      - libgnome-keyring-dev
      - libgconf-2-4
      - libsecret-1-dev
      - xvfb
      - rpm
      - libxext-dev
      - libxtst-dev
      - libxkbfile-dev
      - curl

jobs:
  include:
    - os: linux
      name: Linux Build
      env: CC=gcc-4.8 CXX=g++-4.8
      dist: trusty
      script:
        - npm run lint
        - npm run postinstall
        - DEBUG=electron-packager,electron-osx-sign npm run build
    - os: osx
      name: macOS Build
      osx_image: xcode10.1
      env: CC=clang CXX=clang++ SIGN_BUILD=true
      script:
        - npm run lint
        - npm run postinstall
        - DEBUG=electron-packager,electron-osx-sign npm run build
    - os: windows
      name: Windows Build
      script:
        - powershell npm config set msvs_version 2015
        - powershell npm install && powershell npm run build
        - powershell node app/build/create-windows-installer.js

cache:
  directories:
    - node_modules
    - app/node_modules

deploy:
  skip_cleanup: true
  provider: script
  script:
    - language: bash
    - bash scripts/deploy.sh
  on:
    branch: master
